package com.epam.pharmacy.controller;

public final class ParameterName {
    public static final String LOGIN = "login";
    public static final String PASSWORD = "password";
    public static final String REPEAT_PASSWORD = "repeat_password";
    public static final String LASTNAME = "lastname";
    public static final String NAME = "name";
    public static final String PATRONYMIC = "patronymic";
    public static final String BIRTHDAY_DATE = "birthday_date";
    public static final String SEX = "sex";
    public static final String ROLE = "role";
    public static final String PHONE = "phone";
    public static final String ADDRESS = "address";
    public static final String LANGUAGE = "language";
    public static final String COMMAND = "command";
    public static final String INTERNATIONAL_NAME = "international_name";
    public static final String FORM = "form";
    public static final String DOSAGE = "dosage";
    public static final String DOSAGE_UNIT = "dosage_unit";
    public static final String NEED_PRESCRIPTION = "need_prescription";
    public static final String MANUFACTURER = "manufacturer";
    public static final String NUMBER_IN_PACKAGE = "number_in_package";
    public static final String TOTAL_PACKAGES = "total_packages";
    public static final String PRICE = "price";
    public static final String IMAGE = "image";
    public static final String ORDER_MEDICINE_ID = "order_medicine_id";
    public static final String ORDER_MEDICINE_NUMBER = "order_medicine_number";
    public static final String IMAGE_PATH = "image_path";
    public static final String INTERNATIONAL_NAME_ID="international_name_id";
    public static final String FORM_UNIT = "form_unit";
    public static final String FORM_ID = "form_id";
    public static final String COUNTRY = "country";
    public static final String MANUFACTURER_ID = "manufacturer_id";
    public static final String MEDICINE_ID = "medicine_id";
    public static final String OLD_IMAGE_PATH = "old_image_path";
    public static final String PRESCRIPTION_ID = "prescription_id";
    public static final String PRESCRIPTION_INTERNATIONAL_NAME_ID = "prescription_international_name_id";
    public static final String PRESCRIPTION_DOCTOR_ID = "prescription_doctor_id";
    public static final String PRESCRIPTION_CUSTOMER_ID = "prescription_customer_id";
    public static final String PRESCRIPTION_QUANTITY = "prescription_quantity";
    public static final String PRESCRIPTION_VALIDITY = "prescription_validity";
    public static final String PRESCRIPTION_UNIT = "prescription_unit";
    public static final String PRESCRIPTION_DOSAGE = "prescription_dosage";
    public static final String PRESCRIPTION_DOSAGE_UNIT = "prescription_dosage_unit";
    public static final String INCORRECT_QUANTITY = "incorrect_quantity";
    public static final String USER_FULL_NAME = "user_full_name";
    public static final String SOLD_QUANTITY = "sold_quantity";
    public static final String QUANTITY = "quantity";
    public static final String EXPIRATION_DATE = "expiration_date";
    public static final String CUSTOMER_ID = "customer_id";
    public static final String CUSTOMER_LASTNAME = "customer_lastname";
    public static final String CUSTOMER_NAME = "customer_name";
    public static final String CUSTOMER_PATRONYMIC = "customer_patronymic";
    public static final String CUSTOMER_BIRTHDAY_DATE = "customer_birthday";
    public static final String CUSTOMER_SEX = "customer_sex";
    public static final String SHOW_RENEWAL_REQUESTS = "show_renewal_requests";
    public static final String NEED_RENEWAL = "need_renewal";
    public static final String USER_ROLE = "user_role";
    public static final String USER_LASTNAME = "user_lastname";
    public static final String USER_NAME = "user_name";
    public static final String USER_PATRONYMIC = "user_patronymic";
    public static final String USER_BIRTHDAY_DATE = "user_birthday_date";
    public static final String USER_STATE = "user_state";
    public static final String STATE = "state";
    public static final String MEDICINE = "medicine";
    public static final String CHANGE_TOTAL_VALUE = "change_total_value";
    public static final String MEDICINE_NAME = "medicine_name";
    public static final String MEDICINE_INTERNATIONAL_NAME_ID = "medicine_international_name_id";
    public static final String MEDICINE_FORM_ID = "medicine_form_id";
    public static final String MEDICINE_DOSAGE = "medicine_dosage";
    public static final String MEDICINE_DOSAGE_UNIT = "medicine_dosage_unit";
    public static final String IS_ACTIVE = "is_active";
    public static final String PRESCRIPTION = "prescription";
    public static final String TOTAL_COST = "total_cost";


    private ParameterName() {
    }
}
