package com.epam.pharmacy.controller;

public final class PropertyKey {
    public static final String REGISTRATION_INCORRECT_LASTNAME = "registration.incorrect_lastname";
    public static final String REGISTRATION_INCORRECT_NAME = "registration.incorrect_name";
    public static final String REGISTRATION_INCORRECT_PATRONYMIC = "registration.incorrect_patronymic";
    public static final String REGISTRATION_INCORRECT_ROLE = "registration.incorrect_role";
    public static final String REGISTRATION_INCORRECT_BIRTHDAY_DATE = "registration.incorrect_birthday_date";
    public static final String REGISTRATION_INCORRECT_LOGIN = "registration.incorrect_login";
    public static final String REGISTRATION_INCORRECT_PASSWORD = "registration.incorrect_password";
    public static final String REGISTRATION_INCORRECT_SEX = "registration.incorrect_sex";
    public static final String REGISTRATION_INCORRECT_PHONE = "registration.incorrect_phone";
    public static final String REGISTRATION_INCORRECT_ADDRESS = "registration.incorrect_address";
    public static final String REGISTRATION_INCORRECT_REPEAT_PASSWORD = "registration.incorrect_repeat_password";
    public static final String REGISTRATION_NOT_UNIQUE_LOGIN = "registration.not_unique_login";
    public static final String USERS_DELETED_MESSAGE = "users.deleted_msg";
    public static final String USERS_NOT_DELETED_MESSAGE = "users.not_deleted_msg";
    public static final String USERS_STATE_CHANGED_MESSAGE = "users.state_changed_msg";
    public static final String USERS_STATE_NOT_CHANGED_MESSAGE = "users.state_not_changed_msg";
    public static final String ADDING_MEDICINE_INCORRECT_REQUIRED = "adding_medicine.incorrect_required";
    public static final String ADDING_MEDICINE_INCORRECT_INTERNATIONAL_NAME = "adding_medicine.incorrect_international_name";
    public static final String ADDING_MEDICINE_INCORRECT_FORM = "adding_medicine.incorrect_form";
    public static final String ADDING_MEDICINE_INCORRECT_NOT_INTEGER = "adding_medicine.incorrect_not_integer";
    public static final String ADDING_MEDICINE_INCORRECT_MANUFACTURER = "adding_medicine.incorrect_manufacturer";
    public static final String ADDING_MEDICINE_INCORRECT_PRICE = "adding_medicine.incorrect_price";
    public static final String ADDING_MEDICINE_INCORRECT_DOSAGE_UNIT = "adding_medicine.incorrect_dosage_unit";
    public static final String ADDING_MEDICINE_INCORRECT_FILE_SIZE = "adding_medicine.incorrect_file_size";
    public static final String ADDING_MEDICINE_INCORRECT_FILE_TYPE = "adding_medicine.incorrect_file_type";
    public static final String INTERNATIONAL_NAMES_ADDED = "international_names.added";
    public static final String INTERNATIONAL_NAMES_NOT_ADDED = "international_names.not_added";
    public static final String INTERNATIONAL_NAMES_EDITED = "international_names.edited";
    public static final String INTERNATIONAL_NAMES_NOT_EDITED = "international_names.not_edited";
    public static final String INTERNATIONAL_NAMES_DELETED = "international_names.deleted";
    public static final String INTERNATIONAL_NAMES_NOT_DELETED = "international_names.not_deleted";
    public static final String FORMS_ADDED = "forms.added";
    public static final String FORMS_NOT_ADDED = "forms.not_added";
    public static final String FORMS_EDITED = "forms.edited";
    public static final String FORMS_NOT_EDITED = "forms.not_edited";
    public static final String FORMS_DELETED = "forms.deleted";
    public static final String FORMS_NOT_DELETED = "forms.not_deleted";
    public static final String MANUFACTURERS_ADDED = "manufacturers.added";
    public static final String MANUFACTURERS_NOT_ADDED = "manufacturers.not_added";
    public static final String MANUFACTURERS_EDITED = "manufacturers.edited";
    public static final String MANUFACTURERS_NOT_EDITED = "manufacturers.not_edited";
    public static final String MANUFACTURERS_DELETED = "manufacturers.deleted";
    public static final String MANUFACTURERS_NOT_DELETED = "manufacturers.not_deleted";
    public static final String MEDICINES_NOT_FOUND = "medicines.not_found";
    public static final String EDIT_MEDICINE_SUCCESSFUL_EDITED = "edit_medicine.successful_edited";
    public static final String EDIT_MEDICINE_NOT_EDITED = "edit_medicine.not_edited";
    public static final String PRESCRIPTIONS_SUCCESSFUL_RENEWAL_REQUEST = "prescriptions.successful_renewal_request";
    public static final String PRESCRIPTIONS_FAILED_RENEWAL_REQUEST = "prescriptions.failed_renewal_request";
    public static final String PRESCRIPTIONS_ADDED = "prescriptions.added";
    public static final String ADD_PRESCRIPTION_NOT_ADDED = "add_prescription.not_added";
    public static final String PRESCRIPTIONS_SUCCESSFUL_RENEWAL = "prescriptions.successful_renewal";
    public static final String PRESCRIPTIONS_FAILED_RENEWAL = "prescriptions.failed_renewal";
    public static final String MEDICINES_ADDED_TO_CART = "medicines.added_to_cart";
    public static final String MEDICINES_NOT_ADDED_TO_CART = "medicines.not_added_to_cart";
    public static final String EDIT_MEDICINE_INCORRECT_CHANGE_TOTAL_VALUE = "edit_medicine.incorrect_change_total_value";
    public static final String MEDICINES_PRESCRIPTION_IS_NOT_VALID = "medicines.prescription_is_not_valid";
    public static final String MEDICINES_TOO_BIG_QUANTITY = "medicines.too_big_quantity_msg";
    public static final String PRESCRIPTIONS_NOT_AVAILABLE_IN_CART_YET = "prescriptions.not_available_in_cart_yet";
    public static final String PRESCRIPTIONS_DELETED = "prescriptions.deleted";
    public static final String PRESCRIPTIONS_NOT_DELETED = "prescriptions.not_deleted";
    public static final String CART_DELETED = "cart.deleted";
    public static final String CART_NOT_DELETED = "cart.not_deleted";
    public static final String CART_NOT_CLEARED = "cart.not_cleared";

    private PropertyKey() {
    }
}
